name = "GMW"
uuid = "1819ed89-a2b3-41ea-8dbb-b3a776e027cf"
authors = ["Juraj Lieskovsk√Ω <lieskovsky.juraj@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
